### ISSUE TITLE
There is a attribute naming mismatch between the code and the validation schema

### ISSUE THREAD

**Issue by georgebancila** [mParticle/mparticle-ruby-sdk#12]
I found a mismatch in naming of an attribute. 
It's from the `UserIdentities` module. in the [code](https://github.com/mParticle/mparticle-ruby-sdk/blob/2e7b01c7bb998143a62c85b6e533ac6366973153/lib/mparticle/models/user_identities.rb#L8) is `customerid` but in the [schema](https://docs.mparticle.com/schema/mparticle.inbound.eventsapi.schema.json) is `customer_id`.

I keep receiving Bad Requests when calling mParticle without any given reason (I just receive the code in an error). Do you use the validation schema when validating the requests?

**Comment by samdozor** [comment]
@georgebancila thanks for logging this issue! You're correct that these two are mismatched, but I do not think it would be the reason for your error. Though the official schema is `customer_id`, the Ruby SDK predates this and as it happens we support `customerid` for backwards compatibility. I just tested this and can see my `customerid` value showing up in the mParticle live stream.

Are you receiving an HTTP 400? 401? You should also be receiving a body in the response, which you can inspect by inspecting the return from the synchronous api client signature, or by [setting debugging to `true` in your config](https://github.com/mParticle/mparticle-ruby-sdk/blob/master/lib/mparticle/configuration.rb#L29).

**Comment by georgebancila** [comment]
It was something else that was giving me an error. Thanks!

**Comment by alexs-mparticle** [comment]
Closing this issue as it seems to be self-resolved. Please feel free to reopen if this pops back up again. Thanks
