### ISSUE TITLE
Custom flags send with event

### ISSUE THREAD

**Issue by orubin** [mParticle/mparticle-ruby-sdk#14]
Hi - and sorry for posting an issue.

Didn't find any resource in order to send custom flags (FB / Google data from browser)

https://docs.mparticle.com/developers/server/json-reference/#custom_flags

Any help would be highly appreciated.

Thanks.

**Comment by samdozor** [comment]
hi @orubin no problem at all! The `AppEvent`, `ScreenViewEvent`, and `CommerceEvent` objects each have a `custom_flags` dictionary that you can set:

```ruby
app_event = MParticle::AppEvent.new
app_event.event_name = 'Test event'
app_event.custom_event_type = 'navigation'
app_event.custom_flags = `{ "Google.Category" => "pageview", "Google.Label" => "main:mktg:personal::home", "Google.Value" => "123" }`
```

Let me know if that works for you - will close the issue for now.

**Comment by orubin** [comment]
> hi @orubin no problem at all! The `AppEvent`, `ScreenViewEvent`, and `CommerceEvent` objects each have a `custom_flags` dictionary that you can set:
> 
> ```ruby
> app_event = MParticle::AppEvent.new
> app_event.event_name = 'Test event'
> app_event.custom_event_type = 'navigation'
> app_event.custom_flags = { "Google.Category" => "pageview", "Google.Label" => "main:mktg:personal::home", "Google.Value" => "123" }
> ```
> 
> Let me know if that works for you - will close the issue for now.

Thanks @samdozor 

I am facing a problem like so:
```

irb(main):004:0> app_event = MParticle::AppEvent.new
=> #<MParticle::AppEvent:0x0000557680983400>

irb(main):007:0> app_event.custom_flags = { "Facebook.BrowserId": facebook_browser_id } if facebook_browser_id
NoMethodError: undefined method `custom_flags=' for #<MParticle::AppEvent:0x0000557680983400>
	from (irb):7
	from /app/vendor/bundle/ruby/2.3.0/gems/railties-4.1.3/lib/rails/commands/console.rb:90:in `start'
	from /app/vendor/bundle/ruby/2.3.0/gems/railties-4.1.3/lib/rails/commands/console.rb:9:in `start'
	from /app/vendor/bundle/ruby/2.3.0/gems/railties-4.1.3/lib/rails/commands/commands_tasks.rb:69:in `console'
	from /app/vendor/bundle/ruby/2.3.0/gems/railties-4.1.3/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
	from /app/vendor/bundle/ruby/2.3.0/gems/railties-4.1.3/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```


Using gem mparticle (1.0.2)


Thanks.

**Comment by orubin** [comment]
I have these methods on the app_event:



`
irb(main):010:0> app_event.methods - Object.methods
=> [:to_hash, :valid?, :location, :location=, :session_id, :build_from_hash, :list_invalid_properties, :_deserialize, :to_body, :_to_hash, :timestamp_unixtime_ms, :event_id, :source_message_id, :session_uuid, :custom_attributes, :device_current_state, :custom_event_type, :event_name, :media_info, :timestamp_unixtime_ms=, :event_id=, :source_message_id=, :session_id=, :session_uuid=, :custom_attributes=, :device_current_state=, :custom_event_type=, :event_name=, :media_info=]
irb(main):011:0> 
`

**Comment by orubin** [comment]
Upgrade to 1.0.9?
