### ISSUE TITLE
How do I process an error inside callback provided to `upload_events`?

### ISSUE THREAD

**Issue by NIHERASE** [mParticle/mparticle-ruby-sdk#2]
```ruby
begin
  thread = api_instance.upload_events(batch) do |data, status_code, headers|
    # we check for `response.success?` 
    # so we only get here if the status_code is between 200-299
    if status_code == 202
      puts "Upload complete"
    end
  end

  thread.join 
  # join raises the error that has occurred inside the thread. But this is hardly practical

rescue MParticle::ApiError => e
  puts "Exception when calling mParticle: #{e}"
end
```

I don't see any way how I could catch the `ApiError ` inside this callback. 
In fact it's raised before the callback is invoked:
https://github.com/mParticle/mparticle-ruby-sdk/blob/cade97119e83f7fdf6fd166b83137bca6728c6fe/lib/mparticle/api_client.rb#L72-L92

Also, I don't see why I should check for returned http status codes. I think there's a missing level of abstraction. 

Maybe I'm missing something and this callback is intended for something else :).

**Comment by alexs-mparticle** [comment]
I'm not sure if this helps but this thread goes through the method internally calls the `EventsAPI.upload_events` method.

https://github.com/mParticle/mparticle-ruby-sdk/blob/cade97119e83f7fdf6fd166b83137bca6728c6fe/lib/mparticle/api/events_api.rb#L112

As for the `status_codes`, I believe that is returned just so you handle different errors based on your use case.

Sorry for the late response, but I hope this helps.

Closing this for now, but I can reopen if this is still an issue.
